spring:
  jms:
    servicebus:
      connection-string: ${SERVICE-BUS-CONNECTION}
      idle-timeout: 1800000
      pricing-tier: Standard
      topic-client-id: ${CLIENT-ID}
server:
  port: 2002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
