spring:
  cloud:
    stream:
      bindings:
        userConsumer-in-0:
          destination: users
          group: usersGroup

  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 15672

  application:
    name: consumer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 2003