spring:
  application:
    name: consumer
  rabbitmq:
    password: ${RABBITMQ-PASSWORD}
    username: ${RABBITMQ-USERNAME}
    host: ${RABBITMQ-HOST}
    port: ${RABBITMQ-PORT}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka