spring:
  data:
    mongodb:
      uri: mongodb+srv://anasabbal10:zadina123@cluster0.hebr9ta.mongodb.net/employee
  application:
    name: producer
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 15672
  cloud:
    stream:
      producer:
        produce: false
      default-binder: rabbit
      bindings:
        userProducer-out-0:
          destination: users
          producer:
            required-groups:
              - usersGroup

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
